sonar.projectKey=VynicyusCandido_taskflow-app
sonar.organization=VynicyusCandido
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
sonar.exclusions=**/*.d.ts,src/app/layout.tsx,src/app/page.tsx
