spring.application.name=taskflow
server.port=8080

# Configuração da fonte de dados (PostgreSQL) - com nome do serviço Docker
spring.datasource.url=jdbc:postgresql://postgres:5432/todo_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

debug=true