spring.application.name=taskflow-api

server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?user=postgres.sohafadhunjlnrbypcvp&password=[taskflowvyni]}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:taskflowvyni}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Configuração do Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# CORS Configuration
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,https://taskflow-app-lovat-eta.vercel.app}